# -*- coding: utf-8 -*-
"""5.4.1. Adivina el número.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/153YB4KUoj5CPGvZJGJVP5QUzkOJWXdZU
"""

'''
Clase:        Clase 5
Tema:         Bucles for y while
Ejercicio:    5.4.1. ¡Adivina el número!
Descripción:  Genera un número aleatorio entre 1 y 100 y pide al usuario que lo adivine.
              El programa debe seguir pidiendo números hasta que acierte. En cada
              intento fallido el programa notificará al usuario si el número secreto es
              mayor o menor al último valor ingresado.

Autor:        Rodrigo Lazo
Fecha:        2025-05-31
Estado:       [ Terminado ]
'''
import random

numero = random.randint(1, 100)
while True:
  nuero_usuario = int(input("Adivina el numero entre el 1 al 100: "))

  if nuero_usuario > numero:
    print("El número secreto es menor")
  elif nuero_usuario < numero:
    print("El número secreto es mayor")
  elif nuero_usuario == numero:
    print("¡Felicidades! Has adivinado el número secreto")
    break