# -*- coding: utf-8 -*-
"""5.4.2. Sumador de valores posicionales.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E9amDifX7X3pMVn0H71hb6ysfRnIK_6H
"""

'''
Clase:        Clase 5
Tema:         Bucles for y while
Ejercicio:    5.4.2. Sumador de valores posicionales
Descripción:  Pide un número al usuario y suma sus dígitos hasta que quede un solo dígito.

Autor:        Rodrigo Lazo
Fecha:        2025-05-31
Estado:       [ Terminado ]
'''
numero = int(input("Ingrese un numero grande"))


while numero >= 10:
    suma = 0
    while numero > 0:
        suma += numero % 10
        numero = numero // 10
    numero = suma

print(f"El resultado final es", {numero})