# -*- coding: utf-8 -*-
"""6.3.1. Números líderes.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wx4YoBZWG8rHVcghgsPjhse26B-h7lB0
"""

'''
Clase:        Clase 6
Tema:         tipos de listas y estructuras similares a listas
Ejercicio:    6.3.1. Números líderes
Descripción:  Un número en una lista es "líder" si es
              estrictamente mayor que todos los
              elementos a su derecha. Dada una lista de
              números ingresada por el usuario, imprime
              todos los números líderes

Autor:        Rodrigo Lazo
Fecha:        2025-06-1
Estado:       [ Terminado ]
'''
lista_numeros = input("Ingresa una lista de números separados por espacios: ")
xd = list(map(int, lista_numeros.split()))
numeros_lideres = []

for i in range(len(xd) - 1):
    if xd[i] > xd[i + 1]:
        numeros_lideres.append(xd[i])

print(numeros_lideres)