# -*- coding: utf-8 -*-
"""10.3.1 Matriz simétrica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S6Lk6tUu5kFuEgGCUtUas39vB34xxlhv
"""

'''
Clase:        Clase 10
Tema:         Matrices
Ejercicio:    10.3.1. Matriz simétrica
Descripción:  Dada una matriz cuadrada ingresada por el
              usuario, comprueba si la matriz cuadrada es
              simétrica respecto a su diagonal principal.

Autor:        Rodrigo Lazo
Fecha:        2025-06-11
Estado:       [ Terminado ]
'''

matriz_final = []
n = int(input("Ingrese la dimensión de la matriz: "))

def simetrica(matriz):
    n = len(matriz)
    for i in range(n):
        for j in range(n):
            if matriz[i][j] != matriz[j][i]:
                return False
        return True

for m in range(n):
    fila = list(map(int, input().split(',')))
    matriz_final.append(fila)


if simetrica(matriz_final):
    print("La matriz es simétrica")
else:
    print("La matriz no es simétrica")